# A. Enunciado de la práctica

## 1. Objetivos de la práctica
El desarrollo de esta práctica pretende que el alumnado analice, diseñe e implemente soluciones a un problema usando las técnicas de exploración en espacios de estados impartidas en la asignatura Inteligencia Artificial (IA). Para ello, el alumnado desarrollará de forma grupal (por cuartetos) un proyecto de programación en lenguaje Python mediante el uso del entorno de programación Google Colab y cuadernos de Python.

## 2. Caso de estudio
Se pretende resolver una variante del problema de las reinas de ajedrez, utilizando caballos en su lugar para descubrir cuántos caballos pueden estar presentes en un tablero de ajedrez sin amenazarse mutuamente. Cualquier configuración de caballos en el tablero es válida siempre y cuando no se amenacen mutuamente, pero se desea encontrar el máximo número de caballos. A continuación se ven varios ejemplos sobre un tablero de tamaño 3x3:

```
Optimal and Valid   Valid   Not valid
K·K                 K·K     K··
·K·                 ···     ··K
K·K                 K··     ·K·
```

* Se proporciona un tablero de tamaño MxN (M=Alto, N=Ancho).
* El objetivo del algoritmo es encontrar una configuración válida con el máximo número de caballos posible.
* El movimiento del caballo forma una L en 8 direcciones posibles, consulta la figura para tener una referencia visual:

<img src="https://culturacientifica.com/app/uploads/2022/10/imagen-2-560x553.jpg" alt="drawing" style="width:200px;"/>

## 3. Desarrollo
El desarrollo de esta práctica supone completar este cuaderno de python para resolver el problema para varias configuraciones diferentes usando técnicas de Búsqueda. Además, usando este cuaderno de python, se quieren mostrar resultados de la ejecución de los algoritmos para extraer conclusiones sobre las configuraciones del problema. También se desea hacer una comparativa entre los algoritmos de búsqueda seleccionados.

Es posible que la configuración del problema sea demasiado grande para alguno de los algoritmos. Como regla general, si el algoritmo tarda más de 5 minutos en completar su ejecución se puede declarar que el algoritmo no ha encontrado solución en un tiempo razonable (y lo indicamos en el análisis de resultados)

* Se proporcionan varias configuraciones:
    * Un tablero de **2x2**,
    * Un tablero de **3x3**,
    * Un tablero de **3x5**,
    * Un tablero de **5x5**,
    * Un tablero de **8x8**.
* Se desea aplicar dos algoritmos:
    * **Branch & Bound**: Se quiere obtener una solución óptima, (máximo número de caballos)
    * **A-Star**: Se debe proporcionar (al menos) una heurística admisible para encontrar una solución óptima. En esta memoria se debe justificar que la heurística sea admisible, haciendo la demostración correspondiente.

Para cada configuración y algoritmo se debe proporcionar una tabla de estas características (Puede usarse un generador de tablas https://www.tablesgenerator.com/markdown_tables o pandas https://pandas.pydata.org/docs/user_guide/index.html):

| Tablero | Algoritmo | Tiempo | Caballos |
|---------|-----------|--------|----------|
| 3x3     |  A*       | 3s     | 4        |
| 3x3     |  B&B      | 5s     | 4        |
| 3x5     |  A*       | 10s    | 6        |

## 4. Normativa de la práctica
Para el desarrollo del proyecto de programación se proporciona este cuaderno que sirve a modo de proyecto de programación. Se han propuesto varias configuraciones de tablero para utilizar en las distintas pruebas. Se permiten crear todas las funciones adicionales que sea necesario siempre y cuando se respete la estructura general de este cuaderno. Este cuaderno es el único entregable, por tanto desarrollar código fuera de él no es recomendable.

Además de explicar las decisiones tomadas, será necesario realizar una comparativa de resultados en una o varias tablas, así como incluir una comparativa  final.

La práctica debe realizarse teniendo en cuenta la siguiente normativa:
* NO está permitido alterar los nombres, parámetros ni tipo de retorno de ninguno de los métodos proporcionados. El método modificado se evaluará como 0 así como todos los métodos que dependan de él.
* No está permitido el uso de librerías externas excepto numpy y pandas. El uso de librerías externas hará que se evalúe la práctica como 0.
* La práctica se realizará de forma grupal (grupos de 4 alumnos). Cada grupo deberá desarrollar de manera independiente su propia práctica y realizar su propia entrega.
* El plagio de la práctica queda estrictamente prohibido. La detección de plagio supondrá una calificación de 0 en la convocatoria de la asignatura para todos los alumnos implicados, así como la posibilidad de apertura de expediente académico disciplinar.
* Para ser evaluado de la práctica es obligatorio entregarla en plazo, habiendo realizado correctamente al menos una funcionalidad de las pedidas. Una entrega fuera de plazo será evaluada como 0.
* Usa este cuaderno a modo de memoria, justificando las decisiones que tomes a lo largo del proceso de desarrollo. El desarrollo en texto puntúa de cara a la nota de la práctica.
* De cara a la entrega es estrictamente necesario entregar el cuaderno ejecutado al completo. Una entrega que no haya sido ejecutada con éxito hasta la última celda será evaluada como 0. (Entregad el archivo .ipynb)
* Se debe comentar el código adecuadamente. Este apartado es puntuable.

# Cuerpo de la práctica
Usa las siguientes celdas para desarrollar todo el código pedido. Recuerda respetar esta estructura general y añadir celdas siempre dentro de cada apartado.

## Gestión de estados

### Estado inicial

In [17]:
import numpy as np
def initial_state(M, N):
    # Crea un tablero vacío usando 0s
    board_array = np.zeros((M,N))
    return board_array

In [18]:
# Ejemplo de uso de la función estado inicial
board = initial_state(3, 3)
print(board)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Expansion de estados

In [49]:
import numpy as np
movimientos = [(2,1),(2,-1),(-2,1),(-2,-1),(1,-2),(-1,-2),(1,2), (-1,2)]

def expand(board):
    boards = [] # Crea una lista vacía de tableros
    
    # Crea una lista de tableros con todas las posibles jugadas
    validPositions = getValidPositions(board)
    for i in range(0, len(validPositions)):
        actualPosition = validPositions[i]
        aux = putHorse(board,actualPosition[0],actualPosition[1])
        boards.append(aux.copy())
    return boards # Devolvemos una lista de tableros

def getValidPositions(board):
    
    actual_board = putInvalidPositions(board)
    
    validPositions = []
    dimensions = np.shape(board)
    for i in range(0, dimensions[0]):
        for j in range(0, dimensions[1]):
            if actual_board[i,j] == 0:
                aux = [i,j]
                validPositions.append(aux.copy())
    return validPositions


def putInvalidPositions(board):
    new_board = board.copy()
    horsesPosition = howManyHorses(board)
    dimensions = np.shape(board)
    for y in range(0,len(horsesPosition)):
        
        
        for i in range(0,len(movimientos)):
            aux = horsesPosition[y].copy()
            for j in range(0,2):
                movimientoActual = movimientos[i]
                aux[j] = aux[j] +  movimientoActual[j]
            
            if(aux[0] >= 0 and aux[0] < dimensions[0] and aux[1] >= 0 and aux[1] < dimensions[1]):
                new_board[aux[0],aux[1]] = -1    
    return new_board
   

def howManyHorses(board):
    horses = []
    dimensions = np.shape(board)
    for i in range(0, dimensions[0]):
        for j in range(0, dimensions[1]):
            if board[i,j] == 1:
                aux = [i,j]
                horses.append(aux)
    return horses


def putHorse(board ,i ,j):
    
    new_board = board.copy()
    new_board[i, j] = 1
    
    return new_board

# Pistas:
# - Una función que copie un tablero completo
# - Una función que coloque un caballo en una posición dada en i, j
# - Una estructura de datos con los movimientos posibles para un caballo

In [50]:
expand(board) # Debe devolver una lista de tableros


[array([[1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[0., 1., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[0., 0., 0.],
        [1., 0., 0.],
        [0., 0., 0.]]),
 array([[0., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.]]),
 array([[0., 0., 0.],
        [0., 0., 1.],
        [0., 0., 0.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [1., 0., 0.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 1., 0.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 1.]])]

### Solucion alcanzada

In [21]:
def is_solution(board):
    # Verifica si un tablero es solución
    sol = None
    dimensions = np.shape(board)
    numHorses = (dimensions[0] * dimensions[1]) / 2
    if((len(howManyHorses(board)) >= redondear(numHorses)) and (getValidPositions(board) == [])):
        sol = True
    else: sol = False
    # Haz todas las comprobaciones necesarias para determinar
    # si el tablero es solución

    return sol # Devuelve True si es solución, False en caso contrario

def redondear(n):
    if ((n - int(n)) == 0.5):
        return round(n + 0.1)
    return round(n)


## Métricas

### Funcion de coste

In [ ]:
def cost(path): # path debe contener VARIOS tableros
    # Calcula el coste de un camino
    # Esto debería ser posible: board = path[-1]
    cost = 0
    
    dimensions = np.shape(path)
    for i in range(0,dimensions[0]):
        cost = cost + costUnique(path[i])
    # Calcula el coste de un camino completo

    return cost

def costUnique(board):
    numInvalid = 0
    invalid = putInvalidPositions(board)
    dimensions = np.shape(board)
    for i in range(0, dimensions[0]):
        for j in range(0, dimensions[1]):
            if invalid[i,j] == -1:
                numInvalid = numInvalid + 1
    return  (numInvalid) / 2          
# - Recuerda que A* y B&B funcionan minimizando el coste.
# - ¿Podemos afrontar este problema de otra manera? Maximizar las casillas ocupadas NO funciona...

### Heurística(s)

In [28]:
def heuristic_1(board):
    # Calcula una heurística para un tablero
    heuristic = 0.0
    numValid = 0.0
    # Calcula la heurística de un tablero aquí
    invalid = putInvalidPositions(board)
    dimensions = np.shape(board)
    for i in range(0, dimensions[0]):
        for j in range(0, dimensions[1]):
            if invalid[i,j] == 0:
                numValid = numValid + 1

    if((dimensions[0] * dimensions[1]) < 8 or dimensions[0] == 1 or dimensions[1] == 1):
        return costUnique(board)
    else:
        heuristic = numValid / 2
        return heuristic

# Pista:
# - Al igual que con el coste cuanto menor sea el valor de la heurística mejor, ya que se pretende minimizar.
# - Puedes probar con heuristicas no admisibles, pero al menos una de ellas debe ser admisible para puntuar.

#### Admisibilidad de la heurística
Excepto en los casos base en los que no hay posiciones incorrectas como tableros 1xN o Nx1 y tableros con numero de casillas menor que 8, nuestra heuristica es admisible para el resto de casos siendo siempre menor que el coste del camino real a la solución.

## Algoritmo de búsqueda

### Poda

In [ ]:
def prune(path_list):
    # Si detecta que dos caminos llevan al mismo estado,
    # solo nos interesa aquel camino de menor coste
    # Más adelante usamos la poda despues de ordenar
    for path in path_list[0]:
        currentBoard0 = path[-1]
        for path in path_list[1]:
            currentBoard1 = path[-1]
            if(currentBoard0 == currentBoard1):
                currentCost0 = cost(currentBoard0)
                currentCost1 = cost(currentBoard1)
                if(currentCost0 <= currentCost1):
                    path_list[1].pop(currentBoard1)
                else: path.list[0].pop(currentBoard0)
    return [] # Devuelve una lista de caminos

### Ordenacion

In [ ]:
# *args y **kwargs son argumentos variables, si el argumento no es reconocido es almacenado en estas variables.
# Aquí se utilizan para ignorar argumentos innecesarios.

def order_astar(old_paths, new_paths, c, h, *args, **kwargs):
    # Ordena la lista de caminos segun la heuristica y el coste
    return prune([]) # Devuelve la lista de caminos ordenada y podada segun A*

def order_byb(old_paths, new_paths, c, *args, **kwargs):
    # Ordena la lista de caminos segun el coste
    
    return prune([]) # Devuelve la lista de caminos ordenada y podada segun B&B

### Algoritmo de búsqueda

In [ ]:
def search(initial_board, expansion, cost, heuristic, ordering, solution):
    # Realiza una búsqueda en el espacio de estados
    paths = None # Crea la lista de caminos
    sol = None # Este es el estado solucion
    
    # 1 - Mientras haya caminos y no se haya encontrado solución
    # 2 - Extraer el primer camino
    # 3 - Comprobar si estamos ante un estado solución
    # 4 - Si no es solución, expandir el camino/ Si es solucion, detenemos y vamos al paso 7.
    # 5 - Para cada estado expandido nuevo, añadirlo al camino lo que genera una lista de nuevos caminos
    # 6 - Ordenar los nuevos caminos y viejos caminos, y realizar poda. Volver al paso 1.
    # 7 - Devolver el camino si es solución, si no devolver None

    if len(paths) > 0:
        return sol # Devuelve solo la solucion, no el camino solucion
    else:
        return None

# Experimentos
Usa las funciones `search_horse_byb` y `search_horse_astar` para extraer resultados.

## Utilidades
Usa estas funciones pre-programadas para ejecutar los experimentos y resumir el código.

### Temporizador

In [132]:
################################# NO TOCAR #################################
#                                                                          #
import time

def timer(func):
    def wrapper(*args, **kwargs):
        start = time.time()
        res = func(*args, **kwargs)
        end = time.time()
        print("Executime time: ", end - start, " seconds")
        return res
    return wrapper
#                                                                          #
################################# NO TOCAR #################################

# Este codigo temporiza la ejecución de una función cualquiera

### Envoltorios

In [133]:
################################# NO TOCAR #################################
#                                                                          #
@timer
def search_horse_byb(initial_board):
    return search(initial_board, expand, cost, None, order_byb, is_solution)

@timer
def search_horse_astar(initial_board, heuristic):
    return search(initial_board, expand, cost, heuristic, order_astar, is_solution)
#                                                                          #
################################# NO TOCAR #################################


### Lanzador de experimentos

In [31]:
CONF = {'2x2': (2, 2),
        '3x3': (3, 3),
        '3x5': (3, 5),
        '5x5': (5, 5),
        '8x8': (8, 8),
        }

def measure_solution(board):
    # Devuelve el número de caballos en la solución
    dimensions = np.shape(board)
    for i in range(0, dimensions[0]):
        for j in range(0, dimensions[1]):
            if board[i,j] == 1:
                numHorses = numHorses + 1

    # Es necesario programarla para poder medir la calidad de la solución
    return numHorses

def launch_experiment(configuration, heuristic=None):
    conf = CONF[configuration]
    print(f"Running {'A*' if heuristic else 'B&B'} with {configuration} board")
    if heuristic:
        sol = search_horse_astar(initial_state(*conf), heuristic)
    else:
        sol = search_horse_byb(initial_state(*conf))
    n_c = measure_solution(sol)
    print(f"Solution found: \n{sol}")
    print(f"Number of horses in solution: {n_c}")

    return sol, n_c

## Ejecuciones
Este espacio de la práctica está reservado a las ejecuciones de los algoritmos. Se recomienda el uso del método launch_experiment.

In [32]:
launch_experiment('2x2') # Ejemplo de uso para B&B
print()
launch_experiment('3x5', heuristic=heuristic_1) # Ejemplo de uso para A*
print("Execution finished")

Running B&B with 2x2 board


NameError: name 'search_horse_byb' is not defined

### Branch & Bound

In [ ]:
### Coloca aquí tus experimentos ###

**Resultados de Branch & Bound**

**--> Incluye aquí <--**

La tabla de B&B y una valoración crítica de los resultados.

### A*

In [ ]:
### Coloca aquí tus experimentos ###

**Resultados de A-Star**

**--> Incluye aquí <--**

La tabla de A* y una valoración crítica de los resultados.

## Conclusiones

**--> Incluye aquí <--**

La tabla comparativa entre A* y B&B, añade una valoración crítica de los resultados, especificando las diferencias que encuentras entre ambos algoritmos de búsqueda, ventajas de usar uno sobre otro, el efecto de la configuración del problema, etc.